import color from './colors';

export default {
  Headline: {
    fontFamily: 'Quicksand_700Bold',
    fontWeight: 'bold',
    fontSize: 40,
    lineHeight: 48,
    color: color.primaryColor,
  },
  H1Headline: {
    fontFamily: 'Quicksand_700Bold',
    fontWeight: 'bold',
    fontSize: 36,
    lineHeight: 48,
    color: color.primaryColor,
  },
  H2Headline: {
    fontFamily: 'Quicksand_700Bold',
    fontWeight: 'bold',
    fontSize: 32,
    lineHeight: 40,
    color: color.primaryColor,
  },
  H2HeadlineMuli: {
    fontFamily: 'Muli_700Bold',
    fontWeight: 'bold',
    fontSize: 32,
    lineHeight: 40,
    color: '#212121',
  },
  H3Headline: {
    fontFamily: 'Muli_400Regular',
    fontWeight: 'bold',
    fontSize: 30,
    lineHeight: 40,
    color: color.primaryColor,
  },
  H4Headline: {
    fontFamily: 'Muli_400Regular',
    fontWeight: 'bold',
    fontSize: 26,
    lineHeight: 32,
    color: color.primaryColor,
  },
  H5Headline: {
    fontFamily: 'Muli_400Regular',
    fontWeight: 'bold',
    fontSize: 22,
    lineHeight: 32,
    color: '#212121',
  },
  H5HeadlineQuicksand: {
    fontFamily: 'Quicksand_700Bold',
    fontWeight: 'bold',
    fontSize: 22,
    lineHeight: 32,
    color: color.primaryColor,
  },
  H5HeadlineMedium: {
    fontFamily: 'Muli_600SemiBold',
    fontWeight: 'bold',
    fontSize: 22,
    lineHeight: 32,
    color: color.primaryColor,
  },
  H6Headline: {
    fontFamily: 'Muli_400Regular',
    fontWeight: 'bold',
    fontSize: 18,
    lineHeight: 24,
    color: color.primaryColor,
  },
  S1Subtitle: {
    fontFamily: 'Muli_400Regular',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 24,
    color: color.primaryColor,
  },
  S2Subtitle: {
    fontFamily: 'Muli_400Regular',
    fontSize: 13,
    lineHeight: 24,
    color: color.primaryColor,
  },
  S1Paragraph: {
    fontFamily: 'Muli_400Regular',
    fontSize: 14,
    lineHeight: 20,
    color: color.primaryColor,
  },
  S1ParagraphBold: {
    fontFamily: 'Muli_700Bold',
    fontSize: 14,
    lineHeight: 20,
    color: color.primaryColor,
  },
  S2Paragraph: {
    fontFamily: 'Muli_400Regular',
    fontSize: 12,
    lineHeight: 18,
    color: color.primaryColor,
  },
  C1Caption: {
    fontFamily: 'Muli_400Regular',
    fontSize: 10,
    lineHeight: 16,
    color: color.primaryColor,
  },
  C2Caption: {
    fontFamily: 'Muli_400Regular',
    fontWeight: '600',
    fontSize: 10,
    lineHeight: 16,
    color: color.primaryColor,
  },
  Label: {
    fontFamily: 'Muli_700Bold',
    fontWeight: 'bold',
    fontSize: 12,
    lineHeight: 16,
    color: color.primaryColor,
  },
};
